// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
@ffi.DefaultAsset(
  'package:libserialport_plus/libserialport_plus_bindings.g.dart',
)
library;

import 'dart:ffi' as ffi;
import '' as self;

/// Obtain a pointer to a new sp_port structure representing the named port.
///
/// The user should allocate a variable of type "struct sp_port *" and pass a
/// pointer to this to receive the result.
///
/// The result should be freed after use by calling sp_free_port().
///
/// @param[in] portname The OS-specific name of a serial port. Must not be NULL.
/// @param[out] port_ptr If any error is returned, the variable pointed to by
/// port_ptr will be set to NULL. Otherwise, it will be set
/// to point to the newly allocated port. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<
  ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Pointer<Port>>)
>(symbol: 'sp_get_port_by_name')
external int getPortByName(
  ffi.Pointer<ffi.Char> portname,
  ffi.Pointer<ffi.Pointer<Port>> port_ptr,
);

/// Free a port structure obtained from sp_get_port_by_name() or sp_copy_port().
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @since 0.1.0
@ffi.Native<ffi.Void Function(ffi.Pointer<Port>)>(symbol: 'sp_free_port')
external void freePort(ffi.Pointer<Port> port);

/// List the serial ports available on the system.
///
/// The result obtained is an array of pointers to sp_port structures,
/// terminated by a NULL. The user should allocate a variable of type
/// "struct sp_port **" and pass a pointer to this to receive the result.
///
/// The result should be freed after use by calling sp_free_port_list().
/// If a port from the list is to be used after freeing the list, it must be
/// copied first using sp_copy_port().
///
/// @param[out] list_ptr If any error is returned, the variable pointed to by
/// list_ptr will be set to NULL. Otherwise, it will be set
/// to point to the newly allocated array. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Pointer<ffi.Pointer<Port>>>)>(
  symbol: 'sp_list_ports',
)
external int listPorts(ffi.Pointer<ffi.Pointer<ffi.Pointer<Port>>> list_ptr);

/// Make a new copy of an sp_port structure.
///
/// The user should allocate a variable of type "struct sp_port *" and pass a
/// pointer to this to receive the result.
///
/// The copy should be freed after use by calling sp_free_port().
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[out] copy_ptr If any error is returned, the variable pointed to by
/// copy_ptr will be set to NULL. Otherwise, it will be set
/// to point to the newly allocated copy. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<
  ffi.Int Function(ffi.Pointer<Port>, ffi.Pointer<ffi.Pointer<Port>>)
>(symbol: 'sp_copy_port')
external int copyPort(
  ffi.Pointer<Port> port,
  ffi.Pointer<ffi.Pointer<Port>> copy_ptr,
);

/// Free a port list obtained from sp_list_ports().
///
/// This will also free all the sp_port structures referred to from the list;
/// any that are to be retained must be copied first using sp_copy_port().
///
/// @param[in] ports Pointer to a list of port structures. Must not be NULL.
///
/// @since 0.1.0
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Pointer<Port>>)>(
  symbol: 'sp_free_port_list',
)
external void freePortList(ffi.Pointer<ffi.Pointer<Port>> ports);

/// Open the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] flags Flags to use when opening the serial port.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.UnsignedInt)>(
  symbol: 'sp_open',
)
external int _open(ffi.Pointer<Port> port, int flags);

int open(ffi.Pointer<Port> port, Mode flags) => _open(port, flags.value);

/// Close the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>)>(symbol: 'sp_close')
external int close(ffi.Pointer<Port> port);

/// Get the name of a port.
///
/// The name returned is whatever is normally used to refer to a port on the
/// current operating system; e.g. for Windows it will usually be a "COMn"
/// device name, and for Unix it will be a device path beginning with "/dev/".
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return The port name, or NULL if an invalid port is passed. The name
/// string is part of the port structure and may not be used after
/// the port structure has been freed.
///
/// @since 0.1.0
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<Port>)>(
  symbol: 'sp_get_port_name',
)
external ffi.Pointer<ffi.Char> getPortName(ffi.Pointer<Port> port);

/// Get a description for a port, to present to end user.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return The port description, or NULL if an invalid port is passed.
/// The description string is part of the port structure and may not
/// be used after the port structure has been freed.
///
/// @since 0.1.1
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<Port>)>(
  symbol: 'sp_get_port_description',
)
external ffi.Pointer<ffi.Char> getPortDescription(ffi.Pointer<Port> port);

/// Get the transport type used by a port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return The port transport type.
///
/// @since 0.1.1
@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<Port>)>(
  symbol: 'sp_get_port_transport',
)
external int _getPortTransport(ffi.Pointer<Port> port);

Transport getPortTransport(ffi.Pointer<Port> port) =>
    Transport.fromValue(_getPortTransport(port));

/// Get the USB bus number and address on bus of a USB serial adapter port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[out] usb_bus Pointer to a variable to store the USB bus.
/// Can be NULL (in that case it will be ignored).
/// @param[out] usb_address Pointer to a variable to store the USB address.
/// Can be NULL (in that case it will be ignored).
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.1
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<Port>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
  )
>(symbol: 'sp_get_port_usb_bus_address')
external int getPortUsbBusAddress(
  ffi.Pointer<Port> port,
  ffi.Pointer<ffi.Int> usb_bus,
  ffi.Pointer<ffi.Int> usb_address,
);

/// Get the USB Vendor ID and Product ID of a USB serial adapter port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[out] usb_vid Pointer to a variable to store the USB VID.
/// Can be NULL (in that case it will be ignored).
/// @param[out] usb_pid Pointer to a variable to store the USB PID.
/// Can be NULL (in that case it will be ignored).
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.1
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<Port>,
    ffi.Pointer<ffi.Int>,
    ffi.Pointer<ffi.Int>,
  )
>(symbol: 'sp_get_port_usb_vid_pid')
external int getPortUsbVidPid(
  ffi.Pointer<Port> port,
  ffi.Pointer<ffi.Int> usb_vid,
  ffi.Pointer<ffi.Int> usb_pid,
);

/// Get the USB manufacturer string of a USB serial adapter port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return The port manufacturer string, or NULL if an invalid port is passed.
/// The manufacturer string is part of the port structure and may not
/// be used after the port structure has been freed.
///
/// @since 0.1.1
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<Port>)>(
  symbol: 'sp_get_port_usb_manufacturer',
)
external ffi.Pointer<ffi.Char> getPortUsbManufacturer(ffi.Pointer<Port> port);

/// Get the USB product string of a USB serial adapter port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return The port product string, or NULL if an invalid port is passed.
/// The product string is part of the port structure and may not be
/// used after the port structure has been freed.
///
/// @since 0.1.1
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<Port>)>(
  symbol: 'sp_get_port_usb_product',
)
external ffi.Pointer<ffi.Char> getPortUsbProduct(ffi.Pointer<Port> port);

/// Get the USB serial number string of a USB serial adapter port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return The port serial number, or NULL if an invalid port is passed.
/// The serial number string is part of the port structure and may
/// not be used after the port structure has been freed.
///
/// @since 0.1.1
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<Port>)>(
  symbol: 'sp_get_port_usb_serial',
)
external ffi.Pointer<ffi.Char> getPortUsbSerial(ffi.Pointer<Port> port);

/// Get the MAC address of a Bluetooth serial adapter port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return The port MAC address, or NULL if an invalid port is passed.
/// The MAC address string is part of the port structure and may not
/// be used after the port structure has been freed.
///
/// @since 0.1.1
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<Port>)>(
  symbol: 'sp_get_port_bluetooth_address',
)
external ffi.Pointer<ffi.Char> getPortBluetoothAddress(ffi.Pointer<Port> port);

/// Get the operating system handle for a port.
///
/// The type of the handle depends on the operating system. On Unix based
/// systems, the handle is a file descriptor of type "int". On Windows, the
/// handle is of type "HANDLE". The user should allocate a variable of the
/// appropriate type and pass a pointer to this to receive the result.
///
/// To obtain a valid handle, the port must first be opened by calling
/// sp_open() using the same port structure.
///
/// After the port is closed or the port structure freed, the handle may
/// no longer be valid.
///
/// @warning This feature is provided so that programs may make use of
/// OS-specific functionality where desired. Doing so obviously
/// comes at a cost in portability. It also cannot be guaranteed
/// that direct usage of the OS handle will not conflict with the
/// library's own usage of the port. Be careful.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[out] result_ptr If any error is returned, the variable pointed to by
/// result_ptr will have unknown contents and should not
/// be used. Otherwise, it will be set to point to the
/// OS handle. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Pointer<ffi.Void>)>(
  symbol: 'sp_get_port_handle',
)
external int getPortHandle(
  ffi.Pointer<Port> port,
  ffi.Pointer<ffi.Void> result_ptr,
);

/// Allocate a port configuration structure.
///
/// The user should allocate a variable of type "struct sp_port_config *" and
/// pass a pointer to this to receive the result. The variable will be updated
/// to point to the new configuration structure. The structure is opaque and
/// must be accessed via the functions provided.
///
/// All parameters in the structure will be initialised to special values which
/// are ignored by sp_set_config().
///
/// The structure should be freed after use by calling sp_free_config().
///
/// @param[out] config_ptr If any error is returned, the variable pointed to by
/// config_ptr will be set to NULL. Otherwise, it will
/// be set to point to the allocated config structure.
/// Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Pointer<PortConfig>>)>(
  symbol: 'sp_new_config',
)
external int newConfig(ffi.Pointer<ffi.Pointer<PortConfig>> config_ptr);

/// Free a port configuration structure.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
///
/// @since 0.1.0
@ffi.Native<ffi.Void Function(ffi.Pointer<PortConfig>)>(
  symbol: 'sp_free_config',
)
external void freeConfig(ffi.Pointer<PortConfig> config);

/// Get the current configuration of the specified serial port.
///
/// The user should allocate a configuration structure using sp_new_config()
/// and pass this as the config parameter. The configuration structure will
/// be updated with the port configuration.
///
/// Any parameters that are configured with settings not recognised or
/// supported by libserialport, will be set to special values that are
/// ignored by sp_set_config().
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[out] config Pointer to a configuration structure that will hold
/// the result. Upon errors the contents of the config
/// struct will not be changed. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Pointer<PortConfig>)>(
  symbol: 'sp_get_config',
)
external int getConfig(ffi.Pointer<Port> port, ffi.Pointer<PortConfig> config);

/// Set the configuration for the specified serial port.
///
/// For each parameter in the configuration, there is a special value (usually
/// -1, but see the documentation for each field). These values will be ignored
/// and the corresponding setting left unchanged on the port.
///
/// Upon errors, the configuration of the serial port is unknown since
/// partial/incomplete config updates may have happened.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Pointer<PortConfig>)>(
  symbol: 'sp_set_config',
)
external int setConfig(ffi.Pointer<Port> port, ffi.Pointer<PortConfig> config);

/// Set the baud rate for the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] baudrate Baud rate in bits per second.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Int)>(
  symbol: 'sp_set_baudrate',
)
external int setBaudrate(ffi.Pointer<Port> port, int baudrate);

/// Get the baud rate from a port configuration.
///
/// The user should allocate a variable of type int and
/// pass a pointer to this to receive the result.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[out] baudrate_ptr Pointer to a variable to store the result. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Pointer<ffi.Int>)>(
  symbol: 'sp_get_config_baudrate',
)
external int getConfigBaudrate(
  ffi.Pointer<PortConfig> config,
  ffi.Pointer<ffi.Int> baudrate_ptr,
);

/// Set the baud rate in a port configuration.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[in] baudrate Baud rate in bits per second, or -1 to retain the current setting.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Int)>(
  symbol: 'sp_set_config_baudrate',
)
external int setConfigBaudrate(ffi.Pointer<PortConfig> config, int baudrate);

/// Set the data bits for the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] bits Number of data bits.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Int)>(symbol: 'sp_set_bits')
external int setBits(ffi.Pointer<Port> port, int bits);

/// Get the data bits from a port configuration.
///
/// The user should allocate a variable of type int and
/// pass a pointer to this to receive the result.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[out] bits_ptr Pointer to a variable to store the result. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Pointer<ffi.Int>)>(
  symbol: 'sp_get_config_bits',
)
external int getConfigBits(
  ffi.Pointer<PortConfig> config,
  ffi.Pointer<ffi.Int> bits_ptr,
);

/// Set the data bits in a port configuration.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[in] bits Number of data bits, or -1 to retain the current setting.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Int)>(
  symbol: 'sp_set_config_bits',
)
external int setConfigBits(ffi.Pointer<PortConfig> config, int bits);

/// Set the parity setting for the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] parity Parity setting.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Int)>(
  symbol: 'sp_set_parity',
)
external int _setParity(ffi.Pointer<Port> port, int parity);

int setParity(ffi.Pointer<Port> port, Parity parity) =>
    _setParity(port, parity.value);

/// Get the parity setting from a port configuration.
///
/// The user should allocate a variable of type enum sp_parity and
/// pass a pointer to this to receive the result.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[out] parity_ptr Pointer to a variable to store the result. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Pointer<ffi.Int>)>(
  symbol: 'sp_get_config_parity',
)
external int getConfigParity(
  ffi.Pointer<PortConfig> config,
  ffi.Pointer<ffi.Int> parity_ptr,
);

/// Set the parity setting in a port configuration.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[in] parity Parity setting, or -1 to retain the current setting.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Int)>(
  symbol: 'sp_set_config_parity',
)
external int _setConfigParity(ffi.Pointer<PortConfig> config, int parity);

int setConfigParity(ffi.Pointer<PortConfig> config, Parity parity) =>
    _setConfigParity(config, parity.value);

/// Set the stop bits for the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] stopbits Number of stop bits.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Int)>(
  symbol: 'sp_set_stopbits',
)
external int setStopbits(ffi.Pointer<Port> port, int stopbits);

/// Get the stop bits from a port configuration.
///
/// The user should allocate a variable of type int and
/// pass a pointer to this to receive the result.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[out] stopbits_ptr Pointer to a variable to store the result. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Pointer<ffi.Int>)>(
  symbol: 'sp_get_config_stopbits',
)
external int getConfigStopbits(
  ffi.Pointer<PortConfig> config,
  ffi.Pointer<ffi.Int> stopbits_ptr,
);

/// Set the stop bits in a port configuration.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[in] stopbits Number of stop bits, or -1 to retain the current setting.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Int)>(
  symbol: 'sp_set_config_stopbits',
)
external int setConfigStopbits(ffi.Pointer<PortConfig> config, int stopbits);

/// Set the RTS pin behaviour for the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] rts RTS pin mode.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Int)>(symbol: 'sp_set_rts')
external int _setRts(ffi.Pointer<Port> port, int rts);

int setRts(ffi.Pointer<Port> port, Rts rts) => _setRts(port, rts.value);

/// Get the RTS pin behaviour from a port configuration.
///
/// The user should allocate a variable of type enum sp_rts and
/// pass a pointer to this to receive the result.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[out] rts_ptr Pointer to a variable to store the result. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Pointer<ffi.Int>)>(
  symbol: 'sp_get_config_rts',
)
external int getConfigRts(
  ffi.Pointer<PortConfig> config,
  ffi.Pointer<ffi.Int> rts_ptr,
);

/// Set the RTS pin behaviour in a port configuration.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[in] rts RTS pin mode, or -1 to retain the current setting.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Int)>(
  symbol: 'sp_set_config_rts',
)
external int _setConfigRts(ffi.Pointer<PortConfig> config, int rts);

int setConfigRts(ffi.Pointer<PortConfig> config, Rts rts) =>
    _setConfigRts(config, rts.value);

/// Set the CTS pin behaviour for the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] cts CTS pin mode.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Int)>(symbol: 'sp_set_cts')
external int _setCts(ffi.Pointer<Port> port, int cts);

int setCts(ffi.Pointer<Port> port, Cts cts) => _setCts(port, cts.value);

/// Get the CTS pin behaviour from a port configuration.
///
/// The user should allocate a variable of type enum sp_cts and
/// pass a pointer to this to receive the result.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[out] cts_ptr Pointer to a variable to store the result. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Pointer<ffi.Int>)>(
  symbol: 'sp_get_config_cts',
)
external int getConfigCts(
  ffi.Pointer<PortConfig> config,
  ffi.Pointer<ffi.Int> cts_ptr,
);

/// Set the CTS pin behaviour in a port configuration.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[in] cts CTS pin mode, or -1 to retain the current setting.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Int)>(
  symbol: 'sp_set_config_cts',
)
external int _setConfigCts(ffi.Pointer<PortConfig> config, int cts);

int setConfigCts(ffi.Pointer<PortConfig> config, Cts cts) =>
    _setConfigCts(config, cts.value);

/// Set the DTR pin behaviour for the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] dtr DTR pin mode.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Int)>(symbol: 'sp_set_dtr')
external int _setDtr(ffi.Pointer<Port> port, int dtr);

int setDtr(ffi.Pointer<Port> port, Dtr dtr) => _setDtr(port, dtr.value);

/// Get the DTR pin behaviour from a port configuration.
///
/// The user should allocate a variable of type enum sp_dtr and
/// pass a pointer to this to receive the result.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[out] dtr_ptr Pointer to a variable to store the result. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Pointer<ffi.Int>)>(
  symbol: 'sp_get_config_dtr',
)
external int getConfigDtr(
  ffi.Pointer<PortConfig> config,
  ffi.Pointer<ffi.Int> dtr_ptr,
);

/// Set the DTR pin behaviour in a port configuration.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[in] dtr DTR pin mode, or -1 to retain the current setting.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Int)>(
  symbol: 'sp_set_config_dtr',
)
external int _setConfigDtr(ffi.Pointer<PortConfig> config, int dtr);

int setConfigDtr(ffi.Pointer<PortConfig> config, Dtr dtr) =>
    _setConfigDtr(config, dtr.value);

/// Set the DSR pin behaviour for the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] dsr DSR pin mode.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Int)>(symbol: 'sp_set_dsr')
external int _setDsr(ffi.Pointer<Port> port, int dsr);

int setDsr(ffi.Pointer<Port> port, Dsr dsr) => _setDsr(port, dsr.value);

/// Get the DSR pin behaviour from a port configuration.
///
/// The user should allocate a variable of type enum sp_dsr and
/// pass a pointer to this to receive the result.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[out] dsr_ptr Pointer to a variable to store the result. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Pointer<ffi.Int>)>(
  symbol: 'sp_get_config_dsr',
)
external int getConfigDsr(
  ffi.Pointer<PortConfig> config,
  ffi.Pointer<ffi.Int> dsr_ptr,
);

/// Set the DSR pin behaviour in a port configuration.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[in] dsr DSR pin mode, or -1 to retain the current setting.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Int)>(
  symbol: 'sp_set_config_dsr',
)
external int _setConfigDsr(ffi.Pointer<PortConfig> config, int dsr);

int setConfigDsr(ffi.Pointer<PortConfig> config, Dsr dsr) =>
    _setConfigDsr(config, dsr.value);

/// Set the XON/XOFF configuration for the specified serial port.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] xon_xoff XON/XOFF mode.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Int)>(
  symbol: 'sp_set_xon_xoff',
)
external int _setXonXoff(ffi.Pointer<Port> port, int xon_xoff);

int setXonXoff(ffi.Pointer<Port> port, Xonxoff xon_xoff) =>
    _setXonXoff(port, xon_xoff.value);

/// Get the XON/XOFF configuration from a port configuration.
///
/// The user should allocate a variable of type enum sp_xonxoff and
/// pass a pointer to this to receive the result.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[out] xon_xoff_ptr Pointer to a variable to store the result. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Pointer<ffi.Int>)>(
  symbol: 'sp_get_config_xon_xoff',
)
external int getConfigXonXoff(
  ffi.Pointer<PortConfig> config,
  ffi.Pointer<ffi.Int> xon_xoff_ptr,
);

/// Set the XON/XOFF configuration in a port configuration.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[in] xon_xoff XON/XOFF mode, or -1 to retain the current setting.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.Int)>(
  symbol: 'sp_set_config_xon_xoff',
)
external int _setConfigXonXoff(ffi.Pointer<PortConfig> config, int xon_xoff);

int setConfigXonXoff(ffi.Pointer<PortConfig> config, Xonxoff xon_xoff) =>
    _setConfigXonXoff(config, xon_xoff.value);

/// Set the flow control type in a port configuration.
///
/// This function is a wrapper that sets the RTS, CTS, DTR, DSR and
/// XON/XOFF settings as necessary for the specified flow control
/// type. For more fine-grained control of these settings, use their
/// individual configuration functions.
///
/// @param[in] config Pointer to a configuration structure. Must not be NULL.
/// @param[in] flowcontrol Flow control setting to use.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<PortConfig>, ffi.UnsignedInt)>(
  symbol: 'sp_set_config_flowcontrol',
)
external int _setConfigFlowcontrol(
  ffi.Pointer<PortConfig> config,
  int flowcontrol,
);

int setConfigFlowcontrol(
  ffi.Pointer<PortConfig> config,
  Flowcontrol flowcontrol,
) => _setConfigFlowcontrol(config, flowcontrol.value);

/// Set the flow control type for the specified serial port.
///
/// This function is a wrapper that sets the RTS, CTS, DTR, DSR and
/// XON/XOFF settings as necessary for the specified flow control
/// type. For more fine-grained control of these settings, use their
/// individual configuration functions.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] flowcontrol Flow control setting to use.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.UnsignedInt)>(
  symbol: 'sp_set_flowcontrol',
)
external int _setFlowcontrol(ffi.Pointer<Port> port, int flowcontrol);

int setFlowcontrol(ffi.Pointer<Port> port, Flowcontrol flowcontrol) =>
    _setFlowcontrol(port, flowcontrol.value);

/// Read bytes from the specified serial port, blocking until complete.
///
/// @warning If your program runs on Unix, defines its own signal handlers, and
/// needs to abort blocking reads when these are called, then you
/// should not use this function. It repeats system calls that return
/// with EINTR. To be able to abort a read from a signal handler, you
/// should implement your own blocking read using sp_nonblocking_read()
/// together with a blocking method that makes sense for your program.
/// E.g. you can obtain the file descriptor for an open port using
/// sp_get_port_handle() and use this to call select() or pselect(),
/// with appropriate arrangements to return if a signal is received.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[out] buf Buffer in which to store the bytes read. Must not be NULL.
/// @param[in] count Requested number of bytes to read.
/// @param[in] timeout_ms Timeout in milliseconds, or zero to wait indefinitely.
///
/// @return The number of bytes read on success, or a negative error code. If
/// the number of bytes returned is less than that requested, the
/// timeout was reached before the requested number of bytes was
/// available. If timeout is zero, the function will always return
/// either the requested number of bytes or a negative error code.
///
/// @since 0.1.0
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<Port>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.UnsignedInt,
  )
>(symbol: 'sp_blocking_read')
external int blockingRead(
  ffi.Pointer<Port> port,
  ffi.Pointer<ffi.Void> buf,
  int count,
  int timeout_ms,
);

/// Read bytes from the specified serial port, returning as soon as any data is
/// available.
///
/// @warning If your program runs on Unix, defines its own signal handlers, and
/// needs to abort blocking reads when these are called, then you
/// should not use this function. It repeats system calls that return
/// with EINTR. To be able to abort a read from a signal handler, you
/// should implement your own blocking read using sp_nonblocking_read()
/// together with a blocking method that makes sense for your program.
/// E.g. you can obtain the file descriptor for an open port using
/// sp_get_port_handle() and use this to call select() or pselect(),
/// with appropriate arrangements to return if a signal is received.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[out] buf Buffer in which to store the bytes read. Must not be NULL.
/// @param[in] count Maximum number of bytes to read. Must not be zero.
/// @param[in] timeout_ms Timeout in milliseconds, or zero to wait indefinitely.
///
/// @return The number of bytes read on success, or a negative error code. If
/// the result is zero, the timeout was reached before any bytes were
/// available. If timeout_ms is zero, the function will always return
/// either at least one byte, or a negative error code.
///
/// @since 0.1.1
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<Port>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.UnsignedInt,
  )
>(symbol: 'sp_blocking_read_next')
external int blockingReadNext(
  ffi.Pointer<Port> port,
  ffi.Pointer<ffi.Void> buf,
  int count,
  int timeout_ms,
);

/// Read bytes from the specified serial port, without blocking.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[out] buf Buffer in which to store the bytes read. Must not be NULL.
/// @param[in] count Maximum number of bytes to read.
///
/// @return The number of bytes read on success, or a negative error code. The
/// number of bytes returned may be any number from zero to the maximum
/// that was requested.
///
/// @since 0.1.0
@ffi.Native<
  ffi.Int Function(ffi.Pointer<Port>, ffi.Pointer<ffi.Void>, ffi.Size)
>(symbol: 'sp_nonblocking_read')
external int nonblockingRead(
  ffi.Pointer<Port> port,
  ffi.Pointer<ffi.Void> buf,
  int count,
);

/// Write bytes to the specified serial port, blocking until complete.
///
/// Note that this function only ensures that the accepted bytes have been
/// written to the OS; they may be held in driver or hardware buffers and not
/// yet physically transmitted. To check whether all written bytes have actually
/// been transmitted, use the sp_output_waiting() function. To wait until all
/// written bytes have actually been transmitted, use the sp_drain() function.
///
/// @warning If your program runs on Unix, defines its own signal handlers, and
/// needs to abort blocking writes when these are called, then you
/// should not use this function. It repeats system calls that return
/// with EINTR. To be able to abort a write from a signal handler, you
/// should implement your own blocking write using sp_nonblocking_write()
/// together with a blocking method that makes sense for your program.
/// E.g. you can obtain the file descriptor for an open port using
/// sp_get_port_handle() and use this to call select() or pselect(),
/// with appropriate arrangements to return if a signal is received.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] buf Buffer containing the bytes to write. Must not be NULL.
/// @param[in] count Requested number of bytes to write.
/// @param[in] timeout_ms Timeout in milliseconds, or zero to wait indefinitely.
///
/// @return The number of bytes written on success, or a negative error code.
/// If the number of bytes returned is less than that requested, the
/// timeout was reached before the requested number of bytes was
/// written. If timeout is zero, the function will always return
/// either the requested number of bytes or a negative error code. In
/// the event of an error there is no way to determine how many bytes
/// were sent before the error occurred.
///
/// @since 0.1.0
@ffi.Native<
  ffi.Int Function(
    ffi.Pointer<Port>,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.UnsignedInt,
  )
>(symbol: 'sp_blocking_write')
external int blockingWrite(
  ffi.Pointer<Port> port,
  ffi.Pointer<ffi.Void> buf,
  int count,
  int timeout_ms,
);

/// Write bytes to the specified serial port, without blocking.
///
/// Note that this function only ensures that the accepted bytes have been
/// written to the OS; they may be held in driver or hardware buffers and not
/// yet physically transmitted. To check whether all written bytes have actually
/// been transmitted, use the sp_output_waiting() function. To wait until all
/// written bytes have actually been transmitted, use the sp_drain() function.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] buf Buffer containing the bytes to write. Must not be NULL.
/// @param[in] count Maximum number of bytes to write.
///
/// @return The number of bytes written on success, or a negative error code.
/// The number of bytes returned may be any number from zero to the
/// maximum that was requested.
///
/// @since 0.1.0
@ffi.Native<
  ffi.Int Function(ffi.Pointer<Port>, ffi.Pointer<ffi.Void>, ffi.Size)
>(symbol: 'sp_nonblocking_write')
external int nonblockingWrite(
  ffi.Pointer<Port> port,
  ffi.Pointer<ffi.Void> buf,
  int count,
);

/// Gets the number of bytes waiting in the input buffer.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return Number of bytes waiting on success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>)>(symbol: 'sp_input_waiting')
external int inputWaiting(ffi.Pointer<Port> port);

/// Gets the number of bytes waiting in the output buffer.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return Number of bytes waiting on success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>)>(symbol: 'sp_output_waiting')
external int outputWaiting(ffi.Pointer<Port> port);

/// Flush serial port buffers. Data in the selected buffer(s) is discarded.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] buffers Which buffer(s) to flush.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.UnsignedInt)>(
  symbol: 'sp_flush',
)
external int _flush(ffi.Pointer<Port> port, int buffers);

int flush(ffi.Pointer<Port> port, Buffer buffers) =>
    _flush(port, buffers.value);

/// Wait for buffered data to be transmitted.
///
/// @warning If your program runs on Unix, defines its own signal handlers, and
/// needs to abort draining the output buffer when when these are
/// called, then you should not use this function. It repeats system
/// calls that return with EINTR. To be able to abort a drain from a
/// signal handler, you would need to implement your own blocking
/// drain by polling the result of sp_output_waiting().
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>)>(symbol: 'sp_drain')
external int drain(ffi.Pointer<Port> port);

/// Allocate storage for a set of events.
///
/// The user should allocate a variable of type struct sp_event_set *,
/// then pass a pointer to this variable to receive the result.
///
/// The result should be freed after use by calling sp_free_event_set().
///
/// @param[out] result_ptr If any error is returned, the variable pointed to by
/// result_ptr will be set to NULL. Otherwise, it will
/// be set to point to the event set. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Pointer<EventSet>>)>(
  symbol: 'sp_new_event_set',
)
external int newEventSet(ffi.Pointer<ffi.Pointer<EventSet>> result_ptr);

/// Add events to a struct sp_event_set for a given port.
///
/// The port must first be opened by calling sp_open() using the same port
/// structure.
///
/// After the port is closed or the port structure freed, the results may
/// no longer be valid.
///
/// @param[in,out] event_set Event set to update. Must not be NULL.
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[in] mask Bitmask of events to be waited for.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<
  ffi.Int Function(ffi.Pointer<EventSet>, ffi.Pointer<Port>, ffi.UnsignedInt)
>(symbol: 'sp_add_port_events')
external int addPortEvents(
  ffi.Pointer<EventSet> event_set,
  ffi.Pointer<Port> port,
  int mask,
);

/// Wait for any of a set of events to occur.
///
/// @param[in] event_set Event set to wait on. Must not be NULL.
/// @param[in] timeout_ms Timeout in milliseconds, or zero to wait indefinitely.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<EventSet>, ffi.UnsignedInt)>(
  symbol: 'sp_wait',
)
external int wait(ffi.Pointer<EventSet> event_set, int timeout_ms);

/// Free a structure allocated by sp_new_event_set().
///
/// @param[in] event_set Event set to free. Must not be NULL.
///
/// @since 0.1.0
@ffi.Native<ffi.Void Function(ffi.Pointer<EventSet>)>(
  symbol: 'sp_free_event_set',
)
external void freeEventSet(ffi.Pointer<EventSet> event_set);

/// Gets the status of the control signals for the specified port.
///
/// The user should allocate a variable of type "enum sp_signal" and pass a
/// pointer to this variable to receive the result. The result is a bitmask
/// in which individual signals can be checked by bitwise OR with values of
/// the sp_signal enum.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
/// @param[out] signal_mask Pointer to a variable to receive the result.
/// Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>, ffi.Pointer<ffi.UnsignedInt>)>(
  symbol: 'sp_get_signals',
)
external int getSignals(
  ffi.Pointer<Port> port,
  ffi.Pointer<ffi.UnsignedInt> signal_mask,
);

/// Put the port transmit line into the break state.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>)>(symbol: 'sp_start_break')
external int startBreak(ffi.Pointer<Port> port);

/// Take the port transmit line out of the break state.
///
/// @param[in] port Pointer to a port structure. Must not be NULL.
///
/// @return SP_OK upon success, a negative error code otherwise.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function(ffi.Pointer<Port>)>(symbol: 'sp_end_break')
external int endBreak(ffi.Pointer<Port> port);

/// Get the error code for a failed operation.
///
/// In order to obtain the correct result, this function should be called
/// straight after the failure, before executing any other system operations.
/// The result is thread-specific, and only valid when called immediately
/// after a previous call returning SP_ERR_FAIL.
///
/// @return The system's numeric code for the error that caused the last
/// operation to fail.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function()>(symbol: 'sp_last_error_code')
external int lastErrorCode();

/// Get the error message for a failed operation.
///
/// In order to obtain the correct result, this function should be called
/// straight after the failure, before executing other system operations.
/// The result is thread-specific, and only valid when called immediately
/// after a previous call returning SP_ERR_FAIL.
///
/// @return The system's message for the error that caused the last
/// operation to fail. This string may be allocated by the function,
/// and should be freed after use by calling sp_free_error_message().
///
/// @since 0.1.0
@ffi.Native<ffi.Pointer<ffi.Char> Function()>(symbol: 'sp_last_error_message')
external ffi.Pointer<ffi.Char> lastErrorMessage();

/// Free an error message returned by sp_last_error_message().
///
/// @param[in] message The error message string to free. Must not be NULL.
///
/// @since 0.1.0
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'sp_free_error_message',
)
external void freeErrorMessage(ffi.Pointer<ffi.Char> message);

/// Set the handler function for library debugging messages.
///
/// Debugging messages are generated by the library during each operation,
/// to help in diagnosing problems. The handler will be called for each
/// message. The handler can be set to NULL to ignore all debug messages.
///
/// The handler function should accept a format string and variable length
/// argument list, in the same manner as e.g. printf().
///
/// The default handler is sp_default_debug_handler().
///
/// @param[in] handler The handler function to use. Can be NULL (in that case
/// all debug messages will be ignored).
///
/// @since 0.1.0
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<
      ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char> format)>
    >,
  )
>(symbol: 'sp_set_debug_handler')
external void setDebugHandler(
  ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Char> format)>
  >
  handler,
);

/// Default handler function for library debugging messages.
///
/// This function prints debug messages to the standard error stream if the
/// environment variable LIBSERIALPORT_DEBUG is set. Otherwise, they are
/// ignored.
///
/// @param[in] format The format string to use. Must not be NULL.
/// @param[in] ... The variable length argument list to use.
///
/// @since 0.1.0
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>(
  symbol: 'sp_default_debug_handler',
)
external void defaultDebugHandler(ffi.Pointer<ffi.Char> format);

/// Get the major libserialport package version number.
///
/// @return The major package version number.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function()>(symbol: 'sp_get_major_package_version')
external int getMajorPackageVersion();

/// Get the minor libserialport package version number.
///
/// @return The minor package version number.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function()>(symbol: 'sp_get_minor_package_version')
external int getMinorPackageVersion();

/// Get the micro libserialport package version number.
///
/// @return The micro package version number.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function()>(symbol: 'sp_get_micro_package_version')
external int getMicroPackageVersion();

/// Get the libserialport package version number as a string.
///
/// @return The package version number string. The returned string is
/// static and thus should NOT be free'd by the caller.
///
/// @since 0.1.0
@ffi.Native<ffi.Pointer<ffi.Char> Function()>(
  symbol: 'sp_get_package_version_string',
)
external ffi.Pointer<ffi.Char> getPackageVersionString();

/// Get the "current" part of the libserialport library version number.
///
/// @return The "current" library version number.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function()>(symbol: 'sp_get_current_lib_version')
external int getCurrentLibVersion();

/// Get the "revision" part of the libserialport library version number.
///
/// @return The "revision" library version number.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function()>(symbol: 'sp_get_revision_lib_version')
external int getRevisionLibVersion();

/// Get the "age" part of the libserialport library version number.
///
/// @return The "age" library version number.
///
/// @since 0.1.0
@ffi.Native<ffi.Int Function()>(symbol: 'sp_get_age_lib_version')
external int getAgeLibVersion();

/// Get the libserialport library version number as a string.
///
/// @return The library version number string. The returned string is
/// static and thus should NOT be free'd by the caller.
///
/// @since 0.1.0
@ffi.Native<ffi.Pointer<ffi.Char> Function()>(
  symbol: 'sp_get_lib_version_string',
)
external ffi.Pointer<ffi.Char> getLibVersionString();

const addresses = _SymbolAddresses();

class _SymbolAddresses {
  const _SymbolAddresses();
  ffi.Pointer<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<Port>)>>
  get close => ffi.Native.addressOf(self.close);
}

/// Return values.
sealed class Return {
  /// Operation completed successfully.
  static const OK = 0;

  /// Invalid arguments were passed to the function.
  static const ERR_ARG = -1;

  /// A system error occurred while executing the operation.
  static const ERR_FAIL = -2;

  /// A memory allocation failed while executing the operation.
  static const ERR_MEM = -3;

  /// The requested operation is not supported by this system or device.
  static const ERR_SUPP = -4;
}

/// Port access modes.
enum Mode {
  /// Open port for read access.
  read(1),

  /// Open port for write access.
  write(2),

  /// Open port for read and write access. @since 0.1.1
  readWrite(3);

  final int value;
  const Mode(this.value);

  static Mode fromValue(int value) => switch (value) {
    1 => read,
    2 => write,
    3 => readWrite,
    _ => throw ArgumentError('Unknown value for Mode: $value'),
  };
}

/// Port events.
sealed class Event {
  /// Data received and ready to read.
  static const rxReady = 1;

  /// Ready to transmit new data.
  static const txReady = 2;

  /// Error occurred.
  static const error = 4;
}

/// Buffer selection.
enum Buffer {
  /// Input buffer.
  input(1),

  /// Output buffer.
  output(2),

  /// Both buffers.
  both(3);

  final int value;
  const Buffer(this.value);

  static Buffer fromValue(int value) => switch (value) {
    1 => input,
    2 => output,
    3 => both,
    _ => throw ArgumentError('Unknown value for Buffer: $value'),
  };
}

/// Parity settings.
enum Parity {
  /// Special value to indicate setting should be left alone.
  invalid(-1),

  /// No parity.
  none(0),

  /// Odd parity.
  odd(1),

  /// Even parity.
  even(2),

  /// Mark parity.
  mark(3),

  /// Space parity.
  space(4);

  final int value;
  const Parity(this.value);

  static Parity fromValue(int value) => switch (value) {
    -1 => invalid,
    0 => none,
    1 => odd,
    2 => even,
    3 => mark,
    4 => space,
    _ => throw ArgumentError('Unknown value for Parity: $value'),
  };
}

/// RTS pin behaviour.
enum Rts {
  /// Special value to indicate setting should be left alone.
  invalid(-1),

  /// RTS off.
  off(0),

  /// RTS on.
  on(1),

  /// RTS used for flow control.
  flowControl(2);

  final int value;
  const Rts(this.value);

  static Rts fromValue(int value) => switch (value) {
    -1 => invalid,
    0 => off,
    1 => on,
    2 => flowControl,
    _ => throw ArgumentError('Unknown value for Rts: $value'),
  };
}

/// CTS pin behaviour.
enum Cts {
  /// Special value to indicate setting should be left alone.
  invalid(-1),

  /// CTS ignored.
  ignore(0),

  /// CTS used for flow control.
  flowControl(1);

  final int value;
  const Cts(this.value);

  static Cts fromValue(int value) => switch (value) {
    -1 => invalid,
    0 => ignore,
    1 => flowControl,
    _ => throw ArgumentError('Unknown value for Cts: $value'),
  };
}

/// DTR pin behaviour.
enum Dtr {
  /// Special value to indicate setting should be left alone.
  invalid(-1),

  /// DTR off.
  off(0),

  /// DTR on.
  on(1),

  /// DTR used for flow control.
  flowControl(2);

  final int value;
  const Dtr(this.value);

  static Dtr fromValue(int value) => switch (value) {
    -1 => invalid,
    0 => off,
    1 => on,
    2 => flowControl,
    _ => throw ArgumentError('Unknown value for Dtr: $value'),
  };
}

/// DSR pin behaviour.
enum Dsr {
  /// Special value to indicate setting should be left alone.
  invalid(-1),

  /// DSR ignored.
  ignore(0),

  /// DSR used for flow control.
  flowControl(1);

  final int value;
  const Dsr(this.value);

  static Dsr fromValue(int value) => switch (value) {
    -1 => invalid,
    0 => ignore,
    1 => flowControl,
    _ => throw ArgumentError('Unknown value for Dsr: $value'),
  };
}

/// XON/XOFF flow control behaviour.
enum Xonxoff {
  /// Special value to indicate setting should be left alone.
  invalid(-1),

  /// XON/XOFF disabled.
  disabled(0),

  /// XON/XOFF enabled for input only.
  input(1),

  /// XON/XOFF enabled for output only.
  output(2),

  /// XON/XOFF enabled for input and output.
  inputOutput(3);

  final int value;
  const Xonxoff(this.value);

  static Xonxoff fromValue(int value) => switch (value) {
    -1 => invalid,
    0 => disabled,
    1 => input,
    2 => output,
    3 => inputOutput,
    _ => throw ArgumentError('Unknown value for Xonxoff: $value'),
  };
}

/// Standard flow control combinations.
enum Flowcontrol {
  /// No flow control.
  none(0),

  /// Software flow control using XON/XOFF characters.
  xonXoff(1),

  /// Hardware flow control using RTS/CTS signals.
  rtsCts(2),

  /// Hardware flow control using DTR/DSR signals.
  dtrDsr(3);

  final int value;
  const Flowcontrol(this.value);

  static Flowcontrol fromValue(int value) => switch (value) {
    0 => none,
    1 => xonXoff,
    2 => rtsCts,
    3 => dtrDsr,
    _ => throw ArgumentError('Unknown value for Flowcontrol: $value'),
  };
}

/// Input signals.
sealed class Signal {
  /// Clear to send.
  static const cts = 1;

  /// Data set ready.
  static const dsr = 2;

  /// Data carrier detect.
  static const dcd = 4;

  /// Ring indicator.
  static const ri = 8;
}

/// Transport types.
///
/// @since 0.1.1
enum Transport {
  /// Native platform serial port. @since 0.1.1
  native(0),

  /// USB serial port adapter. @since 0.1.1
  usb(1),

  /// Bluetooth serial port adapter. @since 0.1.1
  bluetooth(2);

  final int value;
  const Transport(this.value);

  static Transport fromValue(int value) => switch (value) {
    0 => native,
    1 => usb,
    2 => bluetooth,
    _ => throw ArgumentError('Unknown value for Transport: $value'),
  };
}

/// @struct sp_port
/// An opaque structure representing a serial port.
final class Port extends ffi.Opaque {}

/// @struct sp_port_config
/// An opaque structure representing the configuration for a serial port.
final class PortConfig extends ffi.Opaque {}

/// @struct sp_event_set
/// A set of handles to wait on for events.
final class EventSet extends ffi.Struct {
  /// Array of OS-specific handles.
  external ffi.Pointer<ffi.Void> handles;

  /// Array of bitmasks indicating which events apply for each handle.
  external ffi.Pointer<ffi.UnsignedInt> masks;

  /// Number of handles.
  @ffi.UnsignedInt()
  external int count;
}

const int packageVersionMajor = 0;

const int packageVersionMinor = 1;

const int packageVersionMicro = 1;

const String packageVersionString = '0.1.1';

const int libVersionCurrent = 1;

const int libVersionRevision = 0;

const int libVersionAge = 1;

const String libVersionString = '1:0:1';
